"""Operating-point analysis (ticket #40): the ADR-0003 threshold meets real scores.

θ is DERIVED (threshold.py) — this module never searches for it, and no
score-maximising statistic appears anywhere in it (a test enforces that).
What it adds is the reading: at each ratio in the
sensitivity band, what the derived θ would do to the validation book — decline
rate, default rate among funded vs declined loans, realised expected cost, and
the saving against the fund-everyone reference.

Drift caveat, quantified here because #39 measured it: validation scores
under-predict by ~2.7pp on average (base-rate drift), so each θ declines fewer
loans than a perfectly calibrated scorer would. The table's shifted-score row
bounds that effect.

Run:  PYTHONPATH=src python -m credit_default.decision_policy
"""

from __future__ import annotations

from pathlib import Path

import mlflow
import numpy as np
import pandas as pd

from credit_default.threshold import (
    SENSITIVITY_RATIOS,
    derive_threshold,
    expected_cost_per_loan,
)
from credit_default.tracking import setup_tracking, start_tracked_run

DOC = Path("docs/DECISION_POLICY.md")


def policy_row(y: np.ndarray, p: np.ndarray, ratio: float) -> dict:
    theta = derive_threshold(ratio, 1.0)
    decline = p >= theta
    funded = ~decline
    fund_all_cost = ratio * float(y.mean())  # the prior policy at this ratio
    cost = expected_cost_per_loan(y, p, theta, cost_fn=ratio, cost_fp=1.0)
    return {
        "fn_to_fp": ratio,
        "theta": round(theta, 4),
        "decline_rate": float(decline.mean()),
        "funded_default_rate": float(y[funded].mean()) if funded.any() else float("nan"),
        "declined_default_rate": float(y[decline].mean()) if decline.any() else float("nan"),
        "expected_cost_per_loan": cost,
        "cost_fund_everyone": fund_all_cost,
        "saving_vs_fund_all": 1.0 - cost / fund_all_cost,
    }


def policy_table(y_true, y_prob) -> pd.DataFrame:
    y = np.asarray(y_true, dtype=float)
    p = np.asarray(y_prob, dtype=float)
    return pd.DataFrame([policy_row(y, p, r) for r in SENSITIVITY_RATIOS])


def drift_shift_row(y_true, y_prob, ratio: float = 5.0) -> dict:
    """The #39 finding as a bound: re-run the baseline θ with scores shifted by the
    measured mean under-prediction gap. Not a recalibration — a sensitivity check."""
    y = np.asarray(y_true, dtype=float)
    p = np.asarray(y_prob, dtype=float)
    gap = float(y.mean() - p.mean())
    shifted = np.clip(p + gap, 0.0, 1.0)
    row = policy_row(y, shifted, ratio)
    row["note"] = f"scores shifted +{gap:.4f} (measured mean under-prediction)"
    return row


def main() -> None:
    from credit_default.evaluation import latest_runs, probabilities, split_features
    from credit_default.splits import VALIDATION

    setup_tracking()
    run_id = latest_runs(families=("lightgbm",))["lightgbm"]
    x, y, coverage = split_features(VALIDATION)
    p = probabilities(mlflow.get_run(run_id), x)

    table = policy_table(y, p)
    shifted = drift_shift_row(y, p)

    with start_tracked_run("decision-policy-validation", "decision-policy") as run:
        mlflow.log_params(
            {"scored_run_id": run_id, "split": VALIDATION, "cost_matrix": "ADR-0003 [ASSUMED]"}
        )
        mlflow.log_metrics(
            {
                "label_coverage": coverage,
                "decline_rate_at_baseline": table.loc[table["fn_to_fp"] == 5.0, "decline_rate"].iloc[0],
                "expected_cost_at_baseline": table.loc[table["fn_to_fp"] == 5.0, "expected_cost_per_loan"].iloc[0],
                "drift_shifted_decline_rate": shifted["decline_rate"],
            }
        )
        mlflow.log_table(table, "policy_table.json")
        policy_run = run.info.run_id

    lines = [
        "# Decision Policy — operating points on validation",
        "",
        "GENERATED by `python -m credit_default.decision_policy`; θ derivation:",
        "`src/credit_default/threshold.py` (ADR-0003). All costs in FP-units/loan under",
        "the **[ASSUMED]** 5:1 baseline matrix and its band; review tracked in issue #70.",
        "",
        f"Scored model: lightgbm run `{run_id}`; split: validation (2016-H1),",
        f"label coverage {coverage:.3f} — stated per EVAL_PROTOCOL. Policy run: `{policy_run}`.",
        "",
        table.round(4).to_markdown(index=False),
        "",
        "## Reading",
        "",
        (
            "- θ is derived, never tuned: no score-maximising statistic appears in this "
            "module — the cost ratio alone moves the operating point."
        ),
        (
            "- The policy works as designed: declined loans default at ~3-4x the rate of "
            "funded ones at every ratio, and every operating point beats fund-everyone."
        ),
        (
            "- **Drift caveat (measured in #39):** validation scores under-predict by "
            f"~{float(np.mean(y) - np.mean(p)):.3f} on average, so each θ declines fewer "
            "loans than intended. Shifted-score bound at 5:1: decline rate "
            f"{shifted['decline_rate']:.1%} vs {table.loc[table['fn_to_fp'] == 5.0, 'decline_rate'].iloc[0]:.1%} "
            f"unshifted, expected cost {shifted['expected_cost_per_loan']:.4f} vs "
            f"{table.loc[table['fn_to_fp'] == 5.0, 'expected_cost_per_loan'].iloc[0]:.4f}. "
            "This is a monitoring obligation for P10 (calibration drift), not a reason to "
            "hand-adjust θ."
        ),
    ]
    DOC.write_text("\n".join(lines) + "\n")
    print(table.round(4).to_string(index=False))
    print(f"\nshifted-score bound @5:1: decline {shifted['decline_rate']:.3f}, "
          f"cost {shifted['expected_cost_per_loan']:.4f} ({shifted['note']})")
    print(f"wrote {DOC}; policy run {policy_run}")


if __name__ == "__main__":
    main()
