"""Segment + fairness slice report (ticket #41, EVAL_PROTOCOL §4, RISK_REGISTER R7).

Per-slice discrimination (PR-AUC), outcome rate, and calibration (mean predicted vs
observed) across: vintage month, purpose, state (top-10 by volume + rest), income
quintile, FICO band. Geographic and income slices are documented because geography
and income are established proxies for protected attributes in US lending — this is
a DOCUMENTATION obligation the project takes on deliberately; it is not a fairness
certification, not a compliance claim, and not legal advice.

term is not sliced: v1 scope is 36-month only (constant by construction).

Run:  PYTHONPATH=src python -m credit_default.slices
"""

from __future__ import annotations

from pathlib import Path

import mlflow
import numpy as np
import pandas as pd
from sklearn.metrics import average_precision_score

from credit_default.tracking import setup_tracking, start_tracked_run

DOC = Path("docs/SLICE_REPORT.md")
TOP_STATES = 10
FICO_EDGES = (0, 660, 680, 700, 720, 740, 1000)
FICO_LABELS = ("<660", "660-679", "680-699", "700-719", "720-739", "740+")


def _slice_metrics(name: str, value: str, y: np.ndarray, p: np.ndarray) -> dict:
    both_classes = 0 < y.mean() < 1
    return {
        "family": name,
        "slice": value,
        "loans": len(y),
        "default_rate": float(y.mean()),
        "mean_predicted": float(p.mean()),
        "calibration_gap": float(p.mean() - y.mean()),
        "pr_auc": float(average_precision_score(y, p)) if both_classes else float("nan"),
        "brier": float(np.mean((p - y) ** 2)),
    }


def slice_frame(x: pd.DataFrame) -> pd.DataFrame:
    """The slice keys, derived once from the feature frame."""
    keys = pd.DataFrame(index=x.index)
    keys["vintage_month"] = x["issue_d"].dt.to_period("M").astype(str)
    keys["purpose"] = x["purpose"].astype(str)
    top = x["addr_state"].value_counts().head(TOP_STATES).index
    keys["state"] = np.where(x["addr_state"].isin(top), x["addr_state"].astype(str), "OTHER")
    keys["income_band"] = pd.qcut(
        x["annual_inc"], 5, labels=[f"Q{i}" for i in range(1, 6)]
    ).astype(str)
    keys["fico_band"] = pd.cut(
        x["fico_range_low"], bins=FICO_EDGES, labels=FICO_LABELS, right=False
    ).astype(str)
    return keys


def slice_report(x: pd.DataFrame, y_true, y_prob) -> pd.DataFrame:
    y = np.asarray(y_true, dtype=float)
    p = np.asarray(y_prob, dtype=float)
    keys = slice_frame(x)
    rows = []
    for family in keys.columns:
        for value, idx in keys.groupby(family, sort=True).indices.items():
            rows.append(_slice_metrics(family, str(value), y[idx], p[idx]))
    return pd.DataFrame(rows)


def flag_notable(report: pd.DataFrame, overall_pr_auc: float) -> pd.DataFrame:
    """Slices deserving human eyes: weak discrimination or a large calibration gap.

    Flagging is surfacing-for-review, not judgement — thresholds are visibility
    heuristics ([ASSUMED]), not fairness criteria.
    """
    sized = report[report["loans"] >= 1000]
    weak = sized["pr_auc"] < 0.8 * overall_pr_auc
    gapped = sized["calibration_gap"].abs() > 0.05
    return sized.loc[weak | gapped].sort_values("pr_auc")


def main() -> None:
    from credit_default.evaluation import latest_runs, probabilities, split_features
    from credit_default.splits import VALIDATION

    setup_tracking()
    run_id = latest_runs(families=("lightgbm",))["lightgbm"]
    x, y, coverage = split_features(VALIDATION)
    p = probabilities(mlflow.get_run(run_id), x)

    report = slice_report(x, y, p)
    overall = float(average_precision_score(y, p))
    notable = flag_notable(report, overall)

    with start_tracked_run("slice-report-validation", "slice-report") as run:
        mlflow.log_params({"scored_run_id": run_id, "split": VALIDATION})
        mlflow.log_metrics(
            {
                "overall_pr_auc": overall,
                "label_coverage": coverage,
                "n_slices": len(report),
                "n_flagged": len(notable),
            }
        )
        mlflow.log_table(report, "slice_report.json")
        slice_run = run.info.run_id

    summary = (
        report[report["family"] != "vintage_month"]
        .groupby("family")[["pr_auc", "calibration_gap"]]
        .agg(["min", "max"])
        .round(4)
    )
    lines = [
        "# Slice Report — validation (2016-H1)",
        "",
        "GENERATED by `python -m credit_default.slices`; full table logged as an artifact",
        f"of tracked run `{slice_run}` (scored model: lightgbm `{run_id}`, label",
        f"coverage {coverage:.3f}).",
        "",
        (
            "**Framing (R7, Charter non-goal 4):** income and geographic slices are "
            "documented because they are established proxies for protected attributes in "
            "US lending. This report is a documentation obligation deliberately taken on; "
            "it is not a fairness certification, not a compliance claim, and not legal "
            "advice. Flagging thresholds are visibility heuristics [ASSUMED], not "
            "fairness criteria."
        ),
        "",
        f"Overall PR-AUC {overall:.4f}. Per-family ranges (excl. vintage months):",
        "",
        summary.to_markdown(),
        "",
        f"## Flagged for review ({len(notable)} slices ≥1000 loans)",
        "",
        "Criteria: PR-AUC < 80% of overall, or |mean predicted − observed| > 5pp.",
        "",
        notable.round(4).to_markdown(index=False) if len(notable) else "*(none flagged)*",
        "",
        "## Reading notes",
        "",
        (
            "- Per-slice PR-AUC is not comparable across slices with different base "
            "rates; read it beside `default_rate`, never alone."
        ),
        (
            "- `calibration_gap` < 0 means the model under-predicts risk for that slice "
            "(consistent with the #39 base-rate-drift finding when uniform); a gap "
            "concentrated in specific slices would be a different, worse problem."
        ),
    ]
    DOC.write_text("\n".join(lines) + "\n")
    print(f"slices: {len(report)} rows, {len(notable)} flagged; overall PR-AUC {overall:.4f}")
    print(notable[["family", "slice", "loans", "default_rate", "mean_predicted", "pr_auc"]]
          .round(4).to_string(index=False) if len(notable) else "(none flagged)")
    print(f"wrote {DOC}; slice run {slice_run}")


if __name__ == "__main__":
    main()
