"""Measure class balance on the labelled population -> docs/CLASS_BALANCE.md.

P2 exit artifact (ticket #22): the numbers P3's metric choices and P5's baselines
rest on. Measured, never estimated.

Run:  PYTHONPATH=src python scripts/class_balance.py
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd

from credit_default.ingest import INTERIM_ACCEPTED
from credit_default.labels import add_labels, labelled_only

OUT = Path("docs/CLASS_BALANCE.md")


def main() -> None:
    df = add_labels(
        pd.read_parquet(INTERIM_ACCEPTED, columns=["issue_d", "term", "loan_status"])
    )
    lab = labelled_only(df)
    lab["year"] = lab["issue_d"].dt.year

    v1 = lab[(lab["term"] == " 36 months") & lab["year"].between(2013, 2015)]

    def block(d: pd.DataFrame) -> tuple[int, int, float]:
        n = len(d)
        pos = int((d["default"] == 1).sum())
        return n, pos, pos / n

    lines = [
        "# Class balance — measured on the labelled population",
        "",
        "GENERATED by `scripts/class_balance.py`; label rule: `src/credit_default/labels.py`.",
        "",
        "| Population | Loans | Defaults | Default rate |",
        "|---|---|---|---|",
    ]
    for name, d in [
        ("All labelled (any term, any vintage)", lab),
        ("36-month, all vintages", lab[lab["term"] == " 36 months"]),
        ("60-month, all vintages", lab[lab["term"] == " 60 months"]),
        ("**v1 training scope: 36-month, 2013–2015**", v1),
    ]:
        n, pos, rate = block(d)
        lines.append(f"| {name} | {n:,} | {pos:,} | {rate:.2%} |")

    lines += ["", "## v1 training scope by vintage year", "",
              "| Year | Loans | Defaults | Default rate |", "|---|---|---|---|"]
    for year, d in v1.groupby("year"):
        n, pos, rate = block(d)
        lines.append(f"| {year} | {n:,} | {pos:,} | {rate:.2%} |")

    n, pos, rate = block(v1)
    lines += [
        "",
        "## Implications (feed into P3)",
        "",
        (
            f"- Imbalance in the v1 scope is roughly **1 : {round((1 - rate) / rate)}** "
            "(defaults : non-defaults) — real but mild; PR-AUC stays the primary metric "
            "(Charter §4.1), and no resampling is justified without evidence it helps."
        ),
        (
            "- The v1 population is large enough "
            f"({n:,} loans, {pos:,} defaults) that metric estimates on vintage slices "
            "remain stable; per-month slices in early years are not (see VINTAGE_NOTES)."
        ),
        (
            "- Default rate RISES across the training window (see per-year table) — "
            "within-window drift exists; P3's split design must not shuffle it away."
        ),
    ]
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT}")
    print(f"v1 scope: {n:,} loans, default rate {rate:.4f}")


if __name__ == "__main__":
    main()
