"""P6 final report (ticket #42): selection justification + the one-shot holdout opening.

Two acts, in order:
1. VALIDATION — justify the selection per EVAL_PROTOCOL §3: month-stratified
   bootstrap of the PR-AUC difference (lightgbm vs logistic); the margin must not
   be noise.
2. HOLDOUT — the frozen split opens, once, with the spelled-out acknowledgment and
   full manifest verification, for the final numbers of the chosen model (with the
   baselines for context). Logged as a tracked run; docs/P6_FINAL_REPORT.md written.

Run:  PYTHONPATH=src python scripts/p6_final_report.py
"""

from __future__ import annotations

from pathlib import Path

import mlflow
import numpy as np
from sklearn.metrics import average_precision_score

from credit_default.calibration import expected_calibration_error, reliability_table
from credit_default.decision_policy import drift_shift_row, policy_table
from credit_default.evaluation import latest_runs, probabilities, split_features
from credit_default.splits import HOLDOUT, VALIDATION
from credit_default.tracking import setup_tracking, start_tracked_run
from credit_default.train import evaluate

DOC = Path("docs/P6_FINAL_REPORT.md")
N_BOOT = 500
SEED = 20260904


def month_stratified_bootstrap_diff(x, y, p_a, p_b, n_boot=N_BOOT, seed=SEED):
    """CI for PR-AUC(a) - PR-AUC(b): resample loans within vintage months."""
    rng = np.random.default_rng(seed)
    months = x["issue_d"].dt.to_period("M").astype(str).to_numpy()
    y = np.asarray(y, dtype=float)
    idx_by_month = [np.flatnonzero(months == m) for m in np.unique(months)]
    diffs = np.empty(n_boot)
    for b in range(n_boot):
        sample = np.concatenate([rng.choice(ix, size=len(ix), replace=True) for ix in idx_by_month])
        diffs[b] = (
            average_precision_score(y[sample], p_a[sample])
            - average_precision_score(y[sample], p_b[sample])
        )
    lo, hi = np.percentile(diffs, [2.5, 97.5])
    return float(diffs.mean()), float(lo), float(hi)


def main() -> None:
    setup_tracking()
    ids = latest_runs(families=("prior", "logistic", "lightgbm"))
    chosen_id = ids["lightgbm"]

    # --- Act 1: selection justification on validation --------------------------------
    x_val, y_val, _ = split_features(VALIDATION)
    p_lgbm = np.asarray(probabilities(mlflow.get_run(chosen_id), x_val))
    p_logit = np.asarray(probabilities(mlflow.get_run(ids["logistic"]), x_val))
    mean_diff, lo, hi = month_stratified_bootstrap_diff(x_val, y_val, p_lgbm, p_logit)
    margin_is_real = lo > 0
    print(f"selection margin (PR-AUC lgbm-logit) on validation: "
          f"{mean_diff:+.4f} [95% CI {lo:+.4f}, {hi:+.4f}] -> "
          f"{'REAL' if margin_is_real else 'NOISE — ties go to the simpler model'}")

    # --- Act 2: the holdout opens (once) ---------------------------------------------
    x_h, y_h, coverage = split_features(
        HOLDOUT, i_understand_this_is_for_final_p6_evaluation=True
    )
    rows = {}
    for name, rid in ids.items():
        p = np.asarray(probabilities(mlflow.get_run(rid), x_h))
        metrics = evaluate(y_h, p, coverage)
        metrics["ece"] = expected_calibration_error(y_h, p)
        rows[name] = (metrics, p)

    _, chosen_p = rows["lightgbm"]
    policy = policy_table(y_h, chosen_p)
    shifted = drift_shift_row(y_h, chosen_p)
    reliability = reliability_table(y_h, chosen_p)

    with start_tracked_run("final-report-holdout", "final-report") as run:
        mlflow.log_params(
            {
                "chosen_run_id": chosen_id,
                "selection_margin_ci": f"[{lo:+.4f}, {hi:+.4f}]",
                "split": HOLDOUT,
                "cost_matrix": "ADR-0003 5:1 [ASSUMED]",
            }
        )
        for name, (metrics, _) in rows.items():
            mlflow.log_metrics({f"{name}__{k}": v for k, v in metrics.items()})
        mlflow.log_metric("label_coverage", coverage)
        mlflow.log_table(policy, "holdout_policy_table.json")
        mlflow.log_table(reliability, "holdout_reliability.json")
        report_run = run.info.run_id

    def m(name, key):
        return rows[name][0][key]

    lines = [
        "# P6 Final Report — holdout (2016-H2), opened once",
        "",
        f"GENERATED by `scripts/p6_final_report.py`. Tracked run `{report_run}`;",
        f"chosen model: lightgbm `{chosen_id}` (ADR-0004). Holdout opened with the",
        "spelled-out acknowledgment; manifest hash + recomputation verified before",
        f"any metric. **Label coverage {coverage:.3f}** — every number below is on the",
        "resolved (fast-resolving, biased) subset; stated per EVAL_PROTOCOL.",
        "",
        "## Selection justification (validation, pre-holdout)",
        "",
        f"Month-stratified bootstrap ({N_BOOT} resamples) of the PR-AUC margin,",
        f"lightgbm − logistic: **{mean_diff:+.4f}, 95% CI [{lo:+.4f}, {hi:+.4f}]** —",
        ("the interval excludes zero: the margin is real, so the simpler-model tie rule "
         "does not bind." if margin_is_real else
         "the interval CONTAINS zero: by protocol the tie goes to the simpler model."),
        "",
        "## Holdout metrics (one shot)",
        "",
        "| model | PR-AUC | ROC-AUC | Brier | ECE | cost/loan @5:1 |",
        "|---|---|---|---|---|---|",
    ]
    for name in ("lightgbm", "logistic", "prior"):
        lines.append(
            f"| {name} | {m(name, 'pr_auc'):.4f} | {m(name, 'roc_auc'):.4f} | "
            f"{m(name, 'brier'):.4f} | {m(name, 'ece'):.4f} | "
            f"{m(name, 'expected_cost_at_5to1'):.4f} |"
        )
    lines += [
        "",
        "## Operating points on holdout (chosen model, ADR-0003 band)",
        "",
        policy.round(4).to_markdown(index=False),
        "",
        (
            f"Drift bound at 5:1: shifting scores by the measured mean under-prediction "
            f"moves the decline rate from "
            f"{policy.loc[policy['fn_to_fp'] == 5.0, 'decline_rate'].iloc[0]:.1%} to "
            f"{shifted['decline_rate']:.1%}."
        ),
        "",
        "## Caveats carried forward (unchanged from validation findings)",
        "",
        "- Under-prediction from base-rate drift (#39): a monitoring obligation for",
        "  P10, not a threshold adjustment.",
        "- Cost matrix remains [ASSUMED] 5:1 pending issue #70; the band above is the",
        "  sensitivity statement.",
        "- Holdout coverage is 60.4%: the resolved subset over-represents fast",
        "  resolution (VINTAGE_NOTES); metrics are honest only WITH that caveat.",
    ]
    DOC.write_text("\n".join(lines) + "\n")
    print(f"holdout coverage {coverage:.3f}")
    for name in ("lightgbm", "logistic", "prior"):
        print(f"  {name:>9}: PR-AUC {m(name, 'pr_auc'):.4f}  ROC {m(name, 'roc_auc'):.4f}  "
              f"ECE {m(name, 'ece'):.4f}  cost@5:1 {m(name, 'expected_cost_at_5to1'):.4f}")
    print(f"wrote {DOC}; report run {report_run}")


if __name__ == "__main__":
    main()
