"""Profile every column of the raw accepted-loans CSV into docs/SCHEMA.md.

Reads the file as strings (no inference) and measures reality per column: null rate,
cardinality, numeric parseability, ranges, top categories. This document is the evidence
base for the Pandera contract (P1) and the leakage ledger (P2) — both are written against
what is measured here, not against Kaggle's documentation.

Run:  PYTHONPATH=src python scripts/profile_schema.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

RAW = Path("data/raw/kaggle/accepted_2007_to_2018Q4.csv")
OUT = Path("docs/SCHEMA.md")
TOPK = 3
CAT_MAX = 30  # <= this many uniques -> treat as categorical, list top values


def fmt_num(x: float) -> str:
    if pd.isna(x):
        return "—"
    if abs(x) >= 1e6 or (abs(x) < 1e-2 and x != 0):
        return f"{x:.3g}"
    return f"{x:g}"


def profile(df: pd.DataFrame) -> list[dict]:
    n = len(df)
    rows = []
    for i, col in enumerate(df.columns, 1):
        s = df[col]
        nulls = s.isna().sum()
        nonnull = s.dropna()
        nunique = nonnull.nunique()
        num = pd.to_numeric(nonnull, errors="coerce")
        num_frac = 0.0 if len(nonnull) == 0 else float(num.notna().mean())
        if num_frac == 1.0 and len(nonnull) > 0:
            kind = "numeric"
            detail = f"range {fmt_num(num.min())} – {fmt_num(num.max())}"
        elif nunique <= CAT_MAX and len(nonnull) > 0:
            kind = "categorical"
            top = nonnull.value_counts().head(TOPK)
            detail = "; ".join(f"`{v}` ({c:,})" for v, c in top.items())
        else:
            kind = "text/mixed" if num_frac == 0 else f"mixed ({num_frac:.0%} numeric)"
            sample = str(nonnull.iloc[0])[:40] if len(nonnull) else ""
            detail = f"e.g. `{sample}`"
        rows.append(
            {
                "#": i,
                "column": col,
                "kind": kind,
                "null_pct": 100 * nulls / n,
                "unique": nunique,
                "detail": detail,
            }
        )
    return rows


def main() -> None:
    print(f"reading {RAW} (all columns as string)...", file=sys.stderr)
    df = pd.read_csv(RAW, dtype="string", low_memory=False)
    n = len(df)
    rows = profile(df)

    lines = [
        "# Schema profile — accepted_2007_to_2018Q4.csv",
        "",
        "GENERATED by `scripts/profile_schema.py` — do not edit by hand; rerun instead.",
        "",
        f"Source: DVC-tracked raw file (md5 `40d0463a883c602e3732b5f821a3dac7`), "
        f"{n:,} rows x {len(df.columns)} columns, read entirely as strings so nothing "
        "is inferred. Includes the 33 footer rows (they are visible below as tiny "
        "null-rate contributions; the ingest module drops them).",
        "",
        "`kind` is measured: *numeric* = every non-null value parses as a number; "
        "*categorical* = ≤30 distinct values (top values shown with counts); "
        "*text/mixed* otherwise.",
        "",
        "| # | column | kind | null % | unique | measured detail |",
        "|---|--------|------|--------|--------|-----------------|",
    ]
    for r in rows:
        lines.append(
            f"| {r['#']} | `{r['column']}` | {r['kind']} | {r['null_pct']:.2f} | "
            f"{r['unique']:,} | {r['detail']} |"
        )
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT} ({len(rows)} columns)", file=sys.stderr)


if __name__ == "__main__":
    main()
